services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: docker-practice-backend

    ports:
      - "4000:4000"

    environment:
      PORT: 4000

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: docker-practice-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped
